services:

  # Database:
  postgres:
    image: postgres:17.5
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: garadb
      POSTGRES_USER: garauser
      POSTGRES_PASSWORD: garapass
    ports:
      - "7100:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - gara_net

  # Message Broker:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    ports:
      - "7200:5672"
      - "7300:15672"
    environment:
      RABBITMQ_DEFAULT_USER: garauser
      RABBITMQ_DEFAULT_PASS: garapass
    volumes:
      - ./rabbitdata:/var/lib/rabbitmq
    networks:
      - gara_net

networks:
  gara_net:
    driver: bridge