spring:

  # App info
  application:
    name: gara-app-backend

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:7100/garadb?createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: garauser
    password: garapass

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 7400

  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 7200
    username: garauser
    password: garapass
    virtual-host: /


server:
  port: 7000

app:
  security:
    key: 7wOfs_4i-VefnbjRLAGywwMQ

  frontend:
    origins:
      - http://localhost:3200
      - http://127.0.0.1:3200

